### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by yinchongcfun** [hzde0128/gomicro_note#1]
14天运行时候,会报这个错误
runtime error: invalid memory address or nil pointer dereference
在这一行
  GetProdList: "data": prodRes.Data,

**Comment by hzde0128** [comment]
测试了没有问题的啊
运行p14的时候，需要运行p13的gRPC服务

gRPC
![image](https://user-images.githubusercontent.com/26091808/78570339-704ffe80-7857-11ea-91de-5f753b23c638.png)

http
![image](https://user-images.githubusercontent.com/26091808/78570583-c15ff280-7857-11ea-847c-590657c427dc.png)

请求商品信息
![image](https://user-images.githubusercontent.com/26091808/78570621-cc1a8780-7857-11ea-94b8-44bc115081ab.png)

如果还发现有，请提供具体的报错信息

**Comment by yinchongcfun** [comment]
谢谢.已经可以了.是P13没有开启,和content-type设置的问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"黄忠德"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月6日(星期一) 晚上10:43
收件人:&nbsp;"hzde0128/gomicro_note"<gomicro_note@noreply.github.com&gt;;
抄送:&nbsp;"1606548133"<1606548133@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [hzde0128/gomicro_note] runtime error: invalid memory address or nil pointer dereference (#1)





 
测试了没有问题的啊
 运行p14的时候，需要运行p13的gRPC服务
 
gRPC
 
 
http
 
 
请求商品信息
 
 
如果还发现有，请提供具体的报错信息
